### ISSUE TITLE
⚔️ 1차 빌드 테스트 필요 목록

### ISSUE THREAD

**Issue by awesomedays** [awesomedays/awesomedays#48]
## 명훈형님
- [ ] #168 뒤끝 로그인 문제 -- 뒤끝 쪽에 문의한 상태, 구글 SDK 설치 필요 가능성 있음 ▶ 대표님께 보고
- [ ] #117 오프라인 보상 지급 및 출력
- [ ] #116 도전모드 결과팝업 출력

## 이사님
- [ ] #180 자동레벨업 버튼 토글 상태 확인
- [ ] #172 빨간콩 작업 -- 누락 여부 파악
- [ ] #167 용사단 성급 필터링 추가
- [ ] #125 진급 / 합성 연출 분화 -- 진도 파악 필요 ▶ AD님께 토스
- [ ] #109 계정버프 기능 + UI 연결
- [ ] #96 자동보스도전 기능 + UI 연결
- [ ] #107 시장 마무리 작업
